---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "actual-budget.fullname" . }}-data
  labels:
    {{- include "actual-budget.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.data.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
