apiVersion: v1
entries:
  beets-flask:
  - apiVersion: v2
    appVersion: stable
    created: "2026-05-05T10:20:31.344308108-04:00"
    description: 'Helm chart for beets-flask — a web UI for the beets music organizer.
      Provides a browser-based interface for importing, tagging, and browsing your
      music library with beets. '
    digest: d1810045e43b9f26557472bfda4d54469ae12a296a7eaae1af95028c7c93604f
    home: https://github.com/pSpitzner/beets-flask
    keywords:
    - music
    - media
    - beets
    - web-ui
    - tagging
    name: beets-flask
    sources:
    - https://github.com/pSpitzner/beets-flask
    - https://github.com/rintaun/homelab-charts/tree/main/charts/beets-flask
    type: application
    urls:
    - https://rintaun.github.io/homelab-charts/charts/beets-flask-0.1.4.tgz
    version: 0.1.4
generated: "2026-05-05T10:20:31.341185051-04:00"
