---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shelfarr.fullname" . }}
  labels:
    {{- include "shelfarr.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shelfarr.selectorLabels" . | nindent 4 }}
