{{- with .Values.ingress.host }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "beets-flask.fullname" $ }}
  labels:
    {{- include "beets-flask.labels" $ | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $.Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ . | quote }}
      secretName: {{ . | quote }}
  rules:
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "beets-flask.fullname" $ }}
                port:
                  name: http
{{- end }}
