---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "papra.fullname" . }}-data
  labels:
    {{- include "papra.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
