{{- if .Values.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "navidrome.secretName" . }}
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secret.oidcClientSecret }}
  oidc-client-secret: {{ .Values.secret.oidcClientSecret | quote }}
  {{- end }}
  {{- if .Values.secret.sessionEncryptionKey }}
  session-encryption-key: {{ .Values.secret.sessionEncryptionKey | quote }}
  {{- end }}
{{- end }}
